# -*- mode: ruby -*-
# vi: set ft=ruby :

# require plugins:
#   vagrant-discsize      : ディスク拡張プラグイン
#   vagrant-hostsupdater  : /etc/hosts にvagrantのIPを登録し `ssh vagrant` で接続できるようにする (mutagenで必須)
#   vagrant-docker-compose: docker-compose インストールパック (普通に入れるとかなり面倒)

hostname = "vagrant"
username = "vagrant"

Vagrant.configure("2") do |config|
  # config.vm.box = "ubuntu/focal64"  # Ubuntu 20.04 LTS
  config.vm.box = "ubuntu/bionic64"  # Ubuntu 18.04 LTS

  config.vm.hostname = hostname
  config.vm.network 'private_network', ip: '192.168.50.10'

  config.vm.provider 'virtualbox' do |vb|
    vb.gui = false
    vb.cpus = 4
    vb.memory = 16384  # メモリ拡張 (16GB)

    # ホストOSが32bitのときに64bitOSを動かす
    vb.customize ["modifyvm", :id, "--ostype", "Ubuntu_64"]

    # VirtualBox6.1.16以降はWSL2と共存できるようになったが、
    # vagrant up時に "SSH auth method:" のところから進まない現象があった。
    # それを回避するための設定。
    # 参考：https://bugs.launchpad.net/cloud-images/+bug/1829625
    vb.customize ["modifyvm", :id, "--nestedpaging", "off"]
    vb.customize ["modifyvm", :id, "--paravirtprovider", "hyperv"]
    vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
    vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]

    # VMのDNS要求を、NAT経由でホストのDNSサーバに対して行う
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

    # DNS要求を処理する際に、ホストのリゾルバ機構を使う
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]

    # USBコントローラ設定 (誤作動するので全部OFFに)
    vb.customize ["modifyvm", :id, "--usb", "off"]
    vb.customize ["modifyvm", :id, "--usbehci", "off"]
    vb.customize ["modifyvm", :id, "--usbxhci", "off"]

    # オーディオ設定 (誤作動するので無効に)
    vb.customize ["modifyvm", :id, "--audio", "none"]
  end

  # config.disksize.size = "100GB"  # require plugin: vagrant-disksize

  # sync options
  config.vm.synced_folder ".", "/home/#{username}", disabled: true  # disable default sync setting
  config.vm.synced_folder "../", "/home/#{username}/dotfiles",
    type: "rsync", rsync__args: ["-a"], rsync__auto: false, owner: username, group: username
  config.vm.synced_folder "~/.ssh", "/home/#{username}/.ssh",
    type: "rsync", rsync__args: ["-a"], rsync__auto: false, owner: username, group: username
  config.vm.synced_folder "~/workspace", "/home/#{username}/workspace",
    type: "rsync", rsync__args: ["-a"], rsync__auto: false, owner: username, group: username

  # docker settings (see versions: https://github.com/docker/compose/releases)
  config.vm.provision :docker
  config.vm.provision :docker_compose, compose_version: "1.29.2"
  
  config.vm.provision :shell, path: "bootstrap.sh"
end
