[[plugins]]  # plantuml シンタックス & プレビュー
repo = 'aklt/plantuml-syntax'
on_ft = 'plantuml'
hook_add = '''
  " filetype=plantuml 時に :make コマンドで同名のpngファイルを生成後プレビューを表示
  execute 'let g:plantuml_executable_script="' GetNvimrcDir() . '/lib/plantuml/plantuml"'
'''

[[plugins]]
repo = 'ambv/black'
on_ft = 'python'

[[plugins]]  # Syntax highlight: toml
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]  # Syntax highlight: nginx.conf
repo = 'chr4/nginx.vim'
on_ft = 'nginx'

[[plugins]]  # gitk サポート for fugitive
repo = 'cohama/agit.vim'
on_source = 'vim-fugitive'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]  # Asynchronous Lint Engine というシンタックスチェッカー (Syntasticの代わり)
repo = 'w0rp/ale'
on_event = 'InsertEnter'
hook_source = 'execute "source " . GetNvimrcDir() . "/plugins/ale.rc.vim"'
hook_add = '''
  nmap <silent> <C-k> <Plug>(ale_previous_wrap)
  nmap <silent> <C-j> <Plug>(ale_next_wrap)
'''

[[plugins]]  # Gist
repo = 'lambdalisue/vim-gista'
on_cmd = ['Gista']

[[plugins]]
repo = 'maximbaz/lightline-ale'
on_source = ['ale', 'lightline']
hook_source = '''
let g:lightline.component_expand = {
\   'linter_checking': 'lightline#ale#checking',
\   'linter_warnings': 'lightline#ale#warnings',
\   'linter_errors': 'lightline#ale#errors',
\   'linter_ok': 'lightline#ale#ok',
\ }
let g:lightline.component_type = {
\   'linter_checking': 'left',
\   'linter_warnings': 'warning',
\   'linter_errors': 'error',
\   'linter_ok': 'left',
\ }
let g:lightline#ale#indicator_checking = "\uf110"
let g:lightline#ale#indicator_warnings = "\uf071 "
let g:lightline#ale#indicator_errors = "\uf05e "
let g:lightline#ale#indicator_ok = "\uf00c"
'''

[[plugins]]
repo = 'osyo-manga/shabadou.vim'
depends = 'vim-quickrun'

[[plugins]]
repo = 'scrooloose/nerdtree'
on_map = {n = '<Plug>'}
on_if = "isdirectory(bufname('%'))"
hook_add = '''
  execute 'source' GetNvimrcDir() . '/plugins/nerdtree.rc.vim'
  nnoremap <silent> <Leader>f :<C-u>call NerdTreeToggle()<CR>
'''

[[plugins]]  # 補完機能 (neovim 用)
repo = 'Shougo/deoplete.nvim'
if = "has('nvim')"
on_event = 'InsertEnter'
hook_source = 'execute "source " . GetNvimrcDir() . "/plugins/deoplete.rc.vim"'

[[plugins]]  # dark powered Unite
repo = 'Shougo/denite.nvim'
rev = '1.2'
on_cmd = ['Denite', 'DeniteBufferDir', 'DeniteCursorWord', 'DeniteProjectDir']
if = 'has("nvim")'
hook_source = 'execute "source " . GetNvimrcDir() . "/plugins/denite.rc.vim"'
hook_add = '''
  nnoremap [denite] <Nop>
  nmap    <Leader>d [denite]

  nnoremap <silent> [denite]b
    \ :<C-u>Denite -highlight-matched-char=PreProc buffer<CR>
  nnoremap <silent> [denite]f
    \ :<C-u>Denite -highlight-matched-char=PreProc file_rec<CR>
  " nnoremap <silent> [denite]r
  "   \ :<C-u>Denite -highlight-matched-char=PreProc register<CR>
  nnoremap <silent> [denite]u
    \ :<C-u>Denite -highlight-matched-char=PreProc file_mru<CR>
  nnoremap <silent> [denite]v
    \ :<C-u>Denite -highlight-matched-char=PreProc grep<CR>
  nnoremap <silent> <C-h>
    \ :<C-u>Denite -highlight-matched-char=PreProc help<CR>
  nnoremap <silent> [denite]<Leader> :<C-u>Denite -resume<CR>
  nnoremap <silent> gv
    \ :<C-u>DeniteCursorWord -highlight-matched-char=PreProc grep<CR>
'''

[[plugins]]  # deoplete: vim の補完
repo = 'Shougo/neco-vim'
on_ft = 'vim'
on_source = 'deoplete.nvim'

[[plugins]]  # deoplete: シンタックスからいろんな言語の補完を頑張る
repo = 'Shougo/neco-syntax'
on_source = 'deoplete.nvim'

# [[plugins]]  # deoplete: ffxiv の補完 (自作)
# repo = 'RentalCat/deoplete-ffxiv'
# on_source = 'deoplete.nvim'

[[plugins]]  # Unite file_mru 用
repo = 'Shougo/neomru.vim'
on_source = 'unite.vim'
hook_add = '''
  let g:unite_source_file_mru_ignore_pattern =
      \ '\~$\|\.\%(o\|exe\|dll\|bak\|zwc\|pyc\|sw[po]\)$'.
      \ '\|\%(^\|/\)\.\%(hg\|git\|bzr\|svn\)\%($\|/\)'.
      \ '\|^\%(\\\\\|/mnt/\|/media/\|/temp/\|/tmp/\|\%(/private\)\=/var/folders/\)'.
      \ '\|\%(^\%(fugitive\)://\)'.
      \ '\|\%(^\%(term\)://\)'.
      \ '\|\%(^\%(gita\)://\)'
'''

[[plugins]]  # Unite  # TODO もう少し便利にしたい
repo = 'Shougo/unite.vim'
on_if = 1
hook_add = '''
  execute 'source' GetNvimrcDir() . '/plugins/unite.rc.vim'

  nnoremap [unite] <Nop>
  nmap    <Leader>u [unite]

  nnoremap <silent> [unite]b
        \ :<C-u>Unite -buffer-name=buffer buffer -auto-preview -start-insert -no-resize<CR>
  nnoremap <silent> [unite]f
        \ :<C-u>execute 'Unite find:' . unite#util#path2project_directory(expand('%'))
        \               . ' -buffer-name=grep(`tabpagenr()`) -auto-preview -no-empty -start-insert'
        \               . ' -ignorecase -smartcase -no-resize'<CR>
  nnoremap <silent> [unite]r
        \ :<C-u>Unite -buffer-name=register -default-action=append register<CR>
  nnoremap <silent> [unite]u
        \ :<C-u>Unite -buffer-name=file_mru file_mru -auto-preview -start-insert -no-resize<CR>
  nnoremap <silent> [unite]v
        \ :<C-u>execute 'Unite grep:' . unite#util#path2project_directory(expand('%'))
        \               . ' -buffer-name=grep(`tabpagenr()`) -auto-preview -no-empty -start-insert'
        \               . ' -ignorecase -smartcase -no-resize'<CR>
  nnoremap <silent> [unite]<Leader>
        \ :<C-u>UniteResume<CR>

  " nnoremap <silent> gv
  "       \ :<C-u>execute 'Unite grep:' . unite#util#path2project_directory(expand('%'))
  "       \               . ' -buffer-name=grep(`tabpagenr()`) -auto-preview -no-empty -start-insert'
  "       \               . ' -ignorecase -smartcase -no-resize'<CR><C-r><C-w><CR>
'''

[[plugins]]  # help を見やすくする unite
repo = 'Shougo/unite-help'
on_source = 'unite.vim'

[[plugins]]
repo = 'sjl/gundo.vim'
on_cmd = 'GundoToggle'
hook_add = '''
  let g:gundo_prefer_python3 = has('python3')
  let g:gundo_right = 1
  let g:gundo_preview_bottom = 1
  nnoremap <silent> U  :<C-u>GundoToggle<CR>
'''

[[plugins]]  # vim のシンタックスチェッカー (パーサ)
repo = 'syngan/vim-vimlint'

[[plugins]]
repo = 'thinca/vim-ft-vim_fold'
on_ft = 'vim'

[[plugins]]
repo = 'thinca/vim-unite-history'
on_source = 'unite.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
on_map = {n = '<Plug>'}
hook_add = 'nmap <silent> <Leader>r <Plug>(quickrun)'

[[plugins]]  # git wrapper
repo = 'tpope/vim-fugitive'
on_cmd = ['Gcommit', 'Gblame', 'Gdiff', 'Ggrep', 'Gstatus']
hook_add = '''
  nnoremap [fugitive]    <Nop>
  nmap <Leader>g  [fugitive]
  nnoremap <silent> [fugitive]c :<C-u>Gcommit<CR>
  nnoremap <silent> [fugitive]b :<C-u>Gblame<CR>
  nnoremap <silent> [fugitive]d :<C-u>Gdiff<CR>
  nnoremap <silent> [fugitive]D :<C-u>Gdiff origin/develop<CR>
  nnoremap <silent> [fugitive]g :<C-u>Ggrep<CR>
  nnoremap <silent> [fugitive]s :<C-u>Gstatus<CR>
'''

[[plugins]]  # コメントアウト補助
repo = 'tyru/caw.vim'
on_map = { nx = '<Plug>'}
hook_add = '''
  function! InitCaw() abort
    if !&l:modifiable
      silent! nunmap <buffer> <C-_>
      silent! xunmap <buffer> <C-_>
    else
      nmap <buffer> <C-_> <Plug>(caw:hatpos:toggle)
      xmap <buffer> <C-_> <Plug>(caw:hatpos:toggle)
    endif
  endfunction
  augroup my_caw
    autocmd!
    autocmd FileType * call InitCaw()
  augroup END
'''

[[plugins]]  # vim のシンタックスチェッカー (本体)
repo = 'ynkdir/vim-vimlparser'

[[plugins]]  # deoplete: python補完 (jedi)
repo = 'zchee/deoplete-jedi'
on_source = 'deoplete.nvim'
on_ft = 'python'
hook_add = '''
  let g:deoplete#omni_patterns = {}
  let g:deoplete#omni_patterns.python = '\%([^. \t]\.\|^\s*@\|^\s*from\s.\+import \|^\s*from \|^\s*import \)\w*'
'''

# [[plugins]]  # global (gtags) コマンドによるコードジャンプサポート
# repo = 'ozelentok/denite-gtags'
# on_cmd = 'DeniteCursorWord'
# on_source = 'denite.nvim'
# hook_add = '''
#   nnoremap <silent> [denite]d
#     \ :<C-u>DeniteCursorWord gtags_def -highlight-matched-char=PreProc -buffer-name=gtags_def<CR>
#   nnoremap <silent> [denite]r
#     \ :<C-u>DeniteCursorWord gtags_ref -highlight-matched-char=PreProc -buffer-name=gtags_ref<CR>
# '''
#
# [[plugins]]  # global (gtags) ファイル自動更新
# repo = 'jsfaint/gen_tags.vim'
# on_source = 'denite-gtags'
# hook_add = '''
#     let g:gen_tags#gtags_auto_gen = 1
#     let g:gen_tags#statusline = 1
# '''
