[[plugins]]  # plantuml シンタックス & プレビュー
repo = 'aklt/plantuml-syntax'
on_ft = 'plantuml'
hook_add = '''
  " filetype=plantuml 時に :make コマンドで同名のpngファイルを生成後プレビューを表示
  execute 'let g:plantuml_executable_script="' GetNvimrcDir() . '/lib/plantuml/plantuml"'
'''

[[plugins]]  # Syntax highlight: toml
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]  # Syntax highlight: nginx.conf
repo = 'chr4/nginx.vim'
on_ft = 'nginx'

[[plugins]]  # Syntax highlight: markdown
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'
hook_source = '''
  let g:vim_markdown_folding_disabled = 1
  let g:vim_markdown_conceal = 0
  let g:vim_markdown_conceal_code_blocks = 0
  let g:vim_markdown_fenced_languages = [
  \   'c++=cpp',
  \   'viml=vim',
  \   'bash=sh',
  \   'ini=dosini',
  \   'py=python',
  \ ]
'''

[[plugins]]  # markdown preview
repo = 'previm/previm'
depends = ['vim-markdown']
on_source = 'vim-markdown'
hook_add = '''
    nnoremap <silent> <C-p> :PrevimOpen<CR>
    let g:previm_enable_realtime=1
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
depends = ['vim-markdown', 'previm']
on_source = 'previm'

[[plugins]]  # gitk サポート for fugitive
repo = 'cohama/agit.vim'
on_source = 'vim-fugitive'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'maximbaz/lightline-ale'
depends = ['ale', 'lightline.vim']
on_source = 'ale'
hook_source = '''
let g:lightline.component_expand = {
\   'linter_checking': 'lightline#ale#checking',
\   'linter_warnings': 'lightline#ale#warnings',
\   'linter_errors': 'lightline#ale#errors',
\   'linter_ok': 'lightline#ale#ok',
\ }
let g:lightline.component_type = {
\   'linter_checking': 'warning',
\   'linter_warnings': 'warning',
\   'linter_errors': 'error',
\   'linter_ok': 'left',
\ }
let g:lightline#ale#indicator_checking = "\uf110"
let g:lightline#ale#indicator_warnings = "\uf071 "
let g:lightline#ale#indicator_errors = "\uf05e "
let g:lightline#ale#indicator_ok = "\uf00c"
'''

[[plugins]]  # Asynchronous Lint Engine というシンタックスチェッカー (Syntasticの代わり)
repo = 'w0rp/ale'
on_ft = ['python', 'vim', 'rust']
hook_source = 'execute "source " . GetNvimrcDir() . "/plugins/ale.rc.vim"'
hook_add = '''
  nmap <silent> <C-k> <Plug>(ale_previous_wrap)
  nmap <silent> <C-j> <Plug>(ale_next_wrap)
'''

[[plugins]]
repo = 'osyo-manga/shabadou.vim'
depends = 'vim-quickrun'

[[plugins]]
repo = 'scrooloose/nerdtree'
on_map = {n = '<Plug>'}
on_if = "isdirectory(bufname('%'))"
hook_add = '''
  execute 'source' GetNvimrcDir() . '/plugins/nerdtree.rc.vim'
  nnoremap <silent> <Leader>f :<C-u>call NerdTreeToggle()<CR>
'''

[[plugins]]  # 補完機能 (neovim 用)
repo = 'Shougo/deoplete.nvim'
if = "has('nvim')"
on_event = 'InsertEnter'
hook_source = 'execute "source " . GetNvimrcDir() . "/plugins/deoplete.rc.vim"'

[[plugins]]  # dark powered Unite
repo = 'Shougo/denite.nvim'
rev = '1.2'
on_cmd = ['Denite', 'DeniteBufferDir', 'DeniteCursorWord', 'DeniteProjectDir']
if = 'has("nvim")'
hook_source = 'execute "source " . GetNvimrcDir() . "/plugins/denite.rc.vim"'
hook_add = '''
  nnoremap [denite] <Nop>
  nmap    <Leader>d [denite]

  nnoremap <silent> [denite]b
    \ :<C-u>Denite -highlight-matched-char=PreProc buffer<CR>
  nnoremap <silent> [denite]f
    \ :<C-u>Denite -highlight-matched-char=PreProc file_rec<CR>
  nnoremap <silent> [denite]r
    \ :<C-u>Denite -highlight-matched-char=PreProc register<CR>
  nnoremap <silent> [denite]u
    \ :<C-u>Denite -highlight-matched-char=PreProc file_mru<CR>
  nnoremap <silent> [denite]v
    \ :<C-u>Denite -highlight-matched-char=PreProc grep<CR>
  nnoremap <silent> <C-h>
    \ :<C-u>Denite -highlight-matched-char=PreProc help<CR>
  nnoremap <silent> [denite]<Leader> :<C-u>Denite -resume<CR>
  nnoremap <silent> gv
    \ :<C-u>DeniteCursorWord -highlight-matched-char=PreProc grep<CR>
'''

[[plugins]]  # deoplete: vim の補完
repo = 'Shougo/neco-vim'
on_ft = 'vim'
on_source = 'deoplete.nvim'

[[plugins]]  # deoplete: シンタックスからいろんな言語の補完を頑張る
repo = 'Shougo/neco-syntax'
on_source = 'deoplete.nvim'

# [[plugins]]  # deoplete: ffxiv の補完 (自作)
# repo = 'RentalCat/deoplete-ffxiv'
# on_source = 'deoplete.nvim'

[[plugins]]  # vim のシンタックスチェッカー (パーサ)
repo = 'syngan/vim-vimlint'

[[plugins]]
repo = 'thinca/vim-ft-vim_fold'
on_ft = 'vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
on_map = {n = '<Plug>'}
hook_add = 'nnoremap <silent> <Leader>r <Plug>(quickrun)'

[[plugins]]  # コメントアウト補助
repo = 'tyru/caw.vim'
on_if = 1
hook_add = '''
  function! InitCaw() abort
    if !&l:modifiable
      silent! nunnoremap <buffer> _
      silent! xunnoremap <buffer> _
      " silent! nunnoremap <buffer> <C-_>
      " silent! xunnoremap <buffer> <C-_>
    else
      nmap <buffer> _ <Plug>(caw:hatpos:toggle)
      xmap <buffer> _ <Plug>(caw:hatpos:toggle)
      " nmap <buffer> <C-_> <Plug>(caw:hatpos:toggle)
      " xmap <buffer> <C-_> <Plug>(caw:hatpos:toggle)
    endif
  endfunction

  augroup my_caw
    autocmd!
    autocmd BufWinEnter * call InitCaw()
  augroup END
'''

[[plugins]]  # vim のシンタックスチェッカー (本体)
repo = 'ynkdir/vim-vimlparser'

[[plugins]]  # deoplete: python補完 (jedi)
repo = 'deoplete-plugins/deoplete-jedi'
on_source = 'deoplete.nvim'
on_ft = 'python'
hook_add = '''
  let g:deoplete#omni_patterns = {}
  let g:deoplete#omni_patterns.python = '\%([^. \t]\.\|^\s*@\|^\s*from\s.\+import \|^\s*from \|^\s*import \)\w*'
'''

[[plugins]]  # rust設定
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_source = '''
    let g:rustfmt_autosave = 0
    let g:rust_doc#define_map_K = 0
'''

# [[plugins]]  # global (gtags) コマンドによるコードジャンプサポート
# repo = 'ozelentok/denite-gtags'
# on_cmd = 'DeniteCursorWord'
# on_source = 'denite.nvim'
# hook_add = '''
#   nnoremap <silent> [denite]d
#     \ :<C-u>DeniteCursorWord gtags_def -highlight-matched-char=PreProc -buffer-name=gtags_def<CR>
#   nnoremap <silent> [denite]r
#     \ :<C-u>DeniteCursorWord gtags_ref -highlight-matched-char=PreProc -buffer-name=gtags_ref<CR>
# '''
#
# [[plugins]]  # global (gtags) ファイル自動更新
# repo = 'jsfaint/gen_tags.vim'
# on_source = 'denite-gtags'
# hook_add = '''
#     let g:gen_tags#gtags_auto_gen = 1
#     let g:gen_tags#statusline = 1
# '''
